### ISSUE TITLE
Where the heck is wrapper coming from? Vite?

### ISSUE THREAD

**Issue by alvarix** [chadcrume/flogger#17]

**Comment by chadcrume** [comment]
No idea what you mean

**Comment by alvarix** [comment]
@chadcrume 
The html with <html><head> etc. 
Cant find anywhere in src

**Comment by chadcrume** [comment]
index.html in the root of the repo

**Comment by chadcrume** [comment]
Why do you need the wrapper?  CSS and other JS modules should be added in Vue
